In [289]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("investmentVC.csv")

In [290]:
df.head()

permalink                name  \
0            /organization/waywire            #waywire   
1  /organization/tv-communications  &TV Communications   
2    /organization/rock-your-paper   'Rock' Your Paper   
3   /organization/in-touch-network   (In)Touch Network   
4   /organization/r-ranch-and-mine  -R- Ranch and Mine   

                    homepage_url  \
0         http://www.waywire.com   
1          http://enjoyandtv.com   
2   http://www.rockyourpaper.org   
3  http://www.InTouchNetwork.com   
4                            NaN   

                                       category_list        market   \
0         |Entertainment|Politics|Social Media|News|          News    
1                                            |Games|         Games    
2                             |Publishing|Education|    Publishing    
3  |Electronics|Guides|Coffee|Restaurants|Music|i...   Electronics    
4                      |Tourism|Entertainment|Games|       Tourism    

   funding_total_usd      status country_code state_code         region  ...  \
0          17,50,000    acquired          USA         NY  New York City  ...   
1          40,00,000   operating          USA         CA    Los Angeles  ...   
2             40,000   operating          EST        NaN        Tallinn  ...   
3          15,00,000   operating          GBR        NaN         London  ...   
4             60,000   operating          USA         TX         Dallas  ...   

  secondary_market  product_crowdfunding round_A round_B round_C  round_D  \
0              0.0                   0.0     0.0     0.0     0.0      0.0   
1              0.0                   0.0     0.0     0.0     0.0      0.0   
2              0.0                   0.0     0.0     0.0     0.0      0.0   
3              0.0                   0.0     0.0     0.0     0.0      0.0   
4              0.0                   0.0     0.0     0.0     0.0      0.0   

  round_E round_F  round_G  round_H  
0     0.0     0.0      0.0      0.0  
1     0.0     0.0      0.0      0.0  
2     0.0     0.0      0.0      0.0  
3     0.0     0.0      0.0      0.0  
4     0.0     0.0      0.0      0.0  

[5 rows x 39 columns]

In [291]:
df = df[[" market ", " funding_total_usd ", "country_code", "founded_year", "status"]]
df = df.rename({" market ": "market", " funding_total_usd ": "funding"}, axis=1)
#df = df.rename({" funding_total_usd ": "funding"}, axis=1)
df.head()

market      funding country_code  founded_year     status
0          News    17,50,000           USA        2012.0   acquired
1         Games    40,00,000           USA           NaN  operating
2    Publishing       40,000           EST        2012.0  operating
3   Electronics    15,00,000           GBR        2011.0  operating
4       Tourism       60,000           USA        2014.0  operating

In [292]:
df['funding'] = df['funding'].str.replace(',', '').str.replace(' -   ', '').str.replace(' ', '').str.replace('  ', '').str.replace('   ', '').str.replace('  ', '').str.replace('    ', '')


In [293]:
df.replace('', np.nan, inplace = True)
df = df.dropna()

In [294]:
df.replace('', np.nan, inplace = True)
df = df.dropna()
df['funding'] = df['funding'].astype(float)

In [295]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28292 entries, 0 to 49437
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   market        28292 non-null  object 
 1   funding       28292 non-null  float64
 2   country_code  28292 non-null  object 
 3   founded_year  28292 non-null  float64
 4   status        28292 non-null  object 
dtypes: float64(2), object(3)
memory usage: 1.3+ MB


In [296]:
df.drop(index=df[df['status'] == 'operating'].index, inplace=True)
df.head()

market     funding country_code  founded_year    status
0           News    1750000.0          USA        2012.0  acquired
20   Curated Web    2535000.0          USA        2010.0  acquired
27     Analytics    1250000.0          USA        2011.0  acquired
30   Curated Web      50000.0          USA        2009.0    closed
62      Software   14000000.0          USA        1990.0  acquired

In [297]:
df = df.dropna()
df.isnull().sum()

market          0
funding         0
country_code    0
founded_year    0
status          0
dtype: int64

In [298]:
df['market'] = df['market'].str.replace(' ', '')
n = 15
df['market'].value_counts()[:n].index.tolist()

['Software',
 'CuratedWeb',
 'Mobile',
 'EnterpriseSoftware',
 'Biotechnology',
 'Advertising',
 'Games',
 'E-Commerce',
 'SocialMedia',
 'Semiconductors',
 'Hardware+Software',
 'Security',
 'WebHosting',
 'CleanTechnology',
 'HealthCare']

In [299]:
df = df.loc[df['market'].isin(['Software',
 'Biotechnology',
 'Mobile',
 'E-Commerce',
 'CuratedWeb',
 'EnterpriseSoftware',
 'HealthCare',
 'Hardware+Software',
 'Advertising',
 'Games',
 'CleanTechnology',
 'HealthandWellness',
 'SocialMedia',
 'Education',
 'Finance'])]

In [300]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2201 entries, 20 to 49430
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   market        2201 non-null   object 
 1   funding       2201 non-null   float64
 2   country_code  2201 non-null   object 
 3   founded_year  2201 non-null   float64
 4   status        2201 non-null   object 
dtypes: float64(2), object(3)
memory usage: 103.2+ KB


In [325]:


df['funding'].astype(int)
df.sort_values(by="funding", ascending=True)
df

market     funding  country_code  founded_year    status
20          3   2535000.0             9        2010.0  acquired
30          3     50000.0             9        2009.0    closed
62         14  14000000.0             9        1990.0  acquired
74          4     50000.0             9        2008.0    closed
123        14     50000.0             9        2010.0    closed
...       ...         ...           ...           ...       ...
49394       4   2700000.0             9        2010.0    closed
49396       0     12000.0             6        2010.0    closed
49413       9   3384225.0             4        2005.0  acquired
49419       1   2257464.0             9        2006.0    closed
49430       1  15419877.0             8        1994.0    closed

[2201 rows x 5 columns]

In [302]:
#df.founded_year = df.founded_year.astype(int)
#df.funding = df.funding.astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2201 entries, 20 to 49430
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   market        2201 non-null   object 
 1   funding       2201 non-null   float64
 2   country_code  2201 non-null   object 
 3   founded_year  2201 non-null   float64
 4   status        2201 non-null   object 
dtypes: float64(2), object(3)
memory usage: 103.2+ KB


In [303]:
df['founded_year'].value_counts()

2010.0    206
2007.0    205
2006.0    199
2008.0    169
2011.0    161
2009.0    159
2005.0    151
2004.0    126
2003.0    110
1999.0    109
2000.0    108
2001.0     93
2002.0     91
2012.0     75
1998.0     46
1997.0     42
1996.0     23
1995.0     20
2013.0     14
1994.0     11
1993.0     10
1983.0      9
1989.0      8
1990.0      8
1985.0      7
1984.0      6
1992.0      5
1991.0      5
1988.0      4
1987.0      4
1982.0      3
1979.0      3
1980.0      2
1986.0      2
1976.0      1
1975.0      1
1969.0      1
1981.0      1
1960.0      1
1934.0      1
1974.0      1
Name: founded_year, dtype: int64

In [304]:
### Cleaning Data ####

df["funding"].unique()

array([ 2535000.,    50000., 14000000., ...,  3384225.,  2257464.,
       15419877.])

In [305]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [306]:
country_map = shorten_categories(df.country_code.value_counts(), 15)
df['country_code'] = df['country_code'].map(country_map)
df.country_code.value_counts()

USA      1694
Other     163
GBR       107
CAN        72
ISR        38
FRA        37
DEU        34
IND        21
ESP        19
CHN        16
Name: country_code, dtype: int64

In [307]:
'''
founded_map = shorten_categories(df.founded_year.value_counts(), 100)
df['founded_year'] = df['founded_year'].map(founded_map)
df.founded_year.value_counts()
'''

"\nfounded_map = shorten_categories(df.founded_year.value_counts(), 100)\ndf['founded_year'] = df['founded_year'].map(founded_map)\ndf.founded_year.value_counts()\n"

In [308]:
df['market'].unique()

array(['CuratedWeb', 'Software', 'E-Commerce', 'Games', 'CleanTechnology',
       'Finance', 'Mobile', 'Biotechnology', 'Advertising', 'HealthCare',
       'EnterpriseSoftware', 'SocialMedia', 'HealthandWellness',
       'Hardware+Software', 'Education'], dtype=object)

In [309]:
#### Unique Values ####

from sklearn.preprocessing import LabelEncoder
market_fit = LabelEncoder()
df['market'] = market_fit.fit_transform(df['market'])
df['market'].unique()

array([ 3, 14,  4,  8,  2,  7, 12,  1,  0, 10,  6, 13, 11,  9,  5])

In [310]:
df['country_code'].unique()
from sklearn.preprocessing import LabelEncoder
country_fit = LabelEncoder()
df['country_code'] = country_fit.fit_transform(df['country_code'])
df['country_code'].unique()

array([9, 8, 5, 1, 4, 6, 2, 3, 0, 7])

In [311]:
'''
df['status'].unique()
from sklearn.preprocessing import LabelEncoder
status_fit = LabelEncoder()
df['status'] = status_fit.fit_transform(df['status'])
df['status'].unique()
'''

"\ndf['status'].unique()\nfrom sklearn.preprocessing import LabelEncoder\nstatus_fit = LabelEncoder()\ndf['status'] = status_fit.fit_transform(df['status'])\ndf['status'].unique()\n"

In [312]:
##### RANDOM FOREST #####

# Import train_test_split function
from sklearn.model_selection import train_test_split

X=df[['market', 'funding', 'country_code', 'founded_year']]  # Features
y=df['status']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [313]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [314]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6505295007564297


In [315]:
y_pred = clf.predict([[1, 100000.0, 1, 2012.0]])

In [316]:
X

market     funding  country_code  founded_year
20          3   2535000.0             9        2010.0
30          3     50000.0             9        2009.0
62         14  14000000.0             9        1990.0
74          4     50000.0             9        2008.0
123        14     50000.0             9        2010.0
...       ...         ...           ...           ...
49394       4   2700000.0             9        2010.0
49396       0     12000.0             6        2010.0
49413       9   3384225.0             4        2005.0
49419       1   2257464.0             9        2006.0
49430       1  15419877.0             8        1994.0

[2201 rows x 4 columns]

In [317]:
X = np.array([["Software", 1000000, "USA", 2011]])
X

array([['Software', '1000000', 'USA', '2011']], dtype='<U21')

In [318]:
X[:, 0] = market_fit.transform(X[:,0])
X[:, 2] = country_fit.transform(X[:,2])
X = X.astype(float)
X


array([[1.400e+01, 1.000e+06, 9.000e+00, 2.011e+03]])

In [319]:
ypred = clf.predict(X)
ypred

array(['closed'], dtype=object)

In [320]:
import pickle

In [321]:
data = {"model": clf, "market_fit": market_fit, "country_fit": country_fit}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [322]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

model_loaded = data["model"]
market_fit = data["market_fit"]
country_fit = data["country_fit"]


In [323]:

y_pred

array(['closed'], dtype=object)